language: c

os: linux
dist: trusty

compiler:  
    - clang

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: 
    - make
    - ./hello Odaceo
    - cd ..

deploy:
  provider: bintray
  file: bintray.json
  user: ${BINTRAY_USER}
  key: ${BINTRAY_PASS}
