language: c

os: linux
dist: trusty

compiler:  
    - gcc
    - clang

before_script:  
    - eval "$(curl -sL https://github.com/odaceo/script-ubuntu-cmake/raw/master/install.sh)"
    - mkdir build
    - cd build
    - cmake ..

script: 
    - make
    - ./hello Odaceo
